outline = [
	"meta",
	"basic",
	"advanced",
	"workflow",
	"blog",
	"packages",
]

[names]
meta = "准备"
basic = "语言基础"
advanced = "语言进阶"
workflow = "工作流程"
packages = "包的使用"
blog = "专题"
knowledge = "相关知识"
